# Clippy configuration for tyl-falkordb-adapter

# TYL Framework standard clippy configuration
# This ensures high code quality and consistency across all TYL modules

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Documentation
missing-docs-in-crate-items = true

# Performance lints
too-many-arguments-threshold = 7
type-complexity-threshold = 250
single-char-lifetime-names-threshold = 4

# Naming conventions
allowed-prefixes = ["to", "as", "into", "from", "with", "without", "is", "has", "get", "set"]

# Avoid false positives for async code
avoid-breaking-exported-api = true

# Allow some common patterns in database/adapter code
allowed = [
    # Allow `expect()` in tests and examples
    "expect_used",
    # Allow `unwrap()` in tests  
    "unwrap_used",
    # Allow multiple boolean params for configuration
    "fn_params_excessive_bools",
    # Allow large enum variants for graph types
    "large_enum_variant",
    # Allow module inception for adapter organization
    "module_inception",
]